- title: "Créer un site personel avec Jekyll"
  url: "https://www.youtube.com/playlist?list=PLLAZ4kZ9dFpOPV5C5Ay0pHaa0RJFhcmcB"
  tags: []

- title: "TLDR Newsletters"
  url: "https://tldr.tech"
  tags: []
